data:
  name: "brenda"
  file_path: "./dataset/temp_dataset_1.csv"
  max_len: 512
  vocab_size: 21
  num_classes: 500
  pad_token_id: 0

distributed: True

optim:
  lr: 1e-5
  warmup: 500
  n_iters: 10000
  eta_min_ratio: 0.01
  grad_clip: 1.0666
  accumulation_step: 4

train:
  batch_size: 64
  save_ckpt_step: 500
  ckpt_dir: './checkpoints'

valid:
  batch_size: 64
  ckpt_path: './checkpoints/ckpt_e_4_s_560500.pt'


model: 
  type: "DDiT"
  d_model: 768
  d_cond: 128
  n_heads: 12
  mlp_mult: 4
  dropout: 0.01
  n_layers: 12

log:
  level: 'INFO'
  freq_step: 100

flow:
  source_distribution: "mask"
  scheduler_type: "poliynomial"
  scheduler_exponent: 1.
  loss_func: "cross_entropy"
  time_epsilon: 0.01
  diffusion_on_pad: false


  

